begin;

create table if not exists public.metrics (
  id bigint generated by default as identity primary key,
  metric_key text unique not null,
  name text not null,
  domain text not null check (domain in ('business', 'health', 'planning')),
  unit text not null default '',
  precision integer not null default 0,
  goal numeric,
  goal_mode text not null default 'higher',
  active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  metric_id bigint not null references public.metrics(id) on delete cascade,
  value numeric not null,
  recorded_on date not null,
  recorded_at timestamptz not null,
  note text not null default '',
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create index if not exists entries_metric_date_idx on public.entries(metric_id, recorded_on);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  domain text not null default 'planning' check (domain in ('business', 'health', 'planning')),
  due_on date,
  priority text not null default 'normal' check (priority in ('high', 'normal', 'low')),
  status text not null default 'open' check (status in ('open', 'done')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  period text not null check (period in ('week', 'month')),
  title text not null,
  summary text not null,
  payload_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.images (
  id uuid primary key default gen_random_uuid(),
  object_path text unique not null,
  original_name text not null,
  mime_type text not null,
  byte_size bigint not null check (byte_size > 0 and byte_size <= 10485760),
  category text not null default 'general',
  related_type text,
  related_id text,
  captured_at timestamptz,
  note text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.metrics enable row level security;
alter table public.entries enable row level security;
alter table public.tasks enable row level security;
alter table public.reports enable row level security;
alter table public.images enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'personal-images',
  'personal-images',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
